version: "3.9"

services:
  web:
    build: ./web
    container_name: web
    restart: always
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./web:/web
    ports:
      - "8000:8000"
