# Generated by Django 4.2 on 2023-04-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MyBook',
            fields=[
            ],
            options={
                'ordering': ['price'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('proxy.book',),
        ),
    ]
